project:
  type: book

book:
  title: "Biological Data Science with R"
  author: "Stephen D. Turner, Ph.D."
  date: "January 1, 2019"
  page-footer:
    left: "&copy; 2019 Stephen D. Turner, Ph.D."
    right:
      - icon: twitter
        href: https://x.com/strnr
      - icon: github
        href: https://github.com/stephenturner
      - icon: linkedin
        href: https://www.linkedin.com/in/turnersd/
      - icon: house-fill
        href: https://stephenturner.us/
      - icon: rss
        href: https://blog.stephenturner.us/
  cover-image: cover.jpg
  favicon: hex.png
  downloads: [pdf, epub]
  site-url: https://bdsr.stephenturner.us/
  repo-url: https://github.com/stephenturner/bdsr
  repo-branch: main
  reader-mode: true


  chapters:
    - index.qmd
    - part: "Core Curriculum"
      chapters:
        - basics.qmd
        - tibbles.qmd
        - dplyr.qmd
        - tidyr.qmd
        - ggplot2.qmd
        - tidyeda.qmd
        - rmarkdown.qmd
    - part: "Electives"
      chapters:
        - stats.qmd
        - survival.qmd
        - predmodeling.qmd
        - textmining.qmd
        - rnaseq.qmd
        - ggtree.qmd
    - references.qmd
  appendices:
    - setup.qmd
    - resources.qmd

bibliography: references.bib

callout-appearance: default
callout-icon: false

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Stephen D. Turner, Ph.D."
  pdf:
    documentclass: scrreprt
  epub:
    theme: default



